# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_cluster', models.IntegerField()),
                ('k_age', models.IntegerField()),
                ('k_drink', models.IntegerField()),
                ('k_education', models.IntegerField()),
                ('k_height', models.IntegerField()),
                ('k_target_sex', models.IntegerField()),
                ('k_zodiac', models.IntegerField()),
                ('k_smoke', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('age', models.IntegerField()),
                ('drink', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('orientation', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=20)),
                ('zodiac', models.CharField(max_length=200)),
                ('smoke', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
